name: Hello, World!
description: Greet someone and record the time
author: GitHub Actions

# Define your outputs here.
outputs:
  spotName:
    description: a random spot name

runs:
  using: docker
  image: Dockerfile